Save LDAP errors in $ldap_err to reduce noise in logs
This fixes https://github.com/UPC/ravada/issues/1377:

```
  When there is LDAP auth configured in the server but SQL users login
  there is a warning in the logs:

    ERROR: Login failed 'carlos' at
    /usr/share/perl5/Ravada/Auth/LDAP.pm line 62.

  The user logs in and everything works as expected, this is a cosmetic
  problem of noise in the log file.

|   | LDAP | SQL |                                              |
|---+------+-----+----------------------------------------------|
| 1 | p    | p   | can't happen, if LDAP passes we return early |
| 2 | p    | f   | if LDAP passes we return early               |
| 3 | f    | p   | nothing is printed because SQL passed        |
| 4 | f    | f   | auth error should be printed                 |
```

We have to fix the 4th case. Previous fix was by checking for
Auth::SQL first but that didn't solve it.

          @frankiejol:
          There is another problem, if the user is only in LDAP the
          call to Ravada::Auth::SQL->new makes it die. So it won't try
          to login in LDAP after that.

So we instead store the LDAP error in a variable `$ldap_err' & print
it later if necessary.

`$ldap_err' is being checked 2 times in this case, before every
`return' statement after it.